apiVersion: v1
kind: Secret
metadata:
  name: nextcloud-prod-db-url
  namespace: nextcloud-prod
type: Opaque
stringData:
  url: postgres://nextcloud-prod:{{ postgres_nextcloud_prod_pass }}@nextcloud-prod-rw.cloudnative-pg.svc.cluster.local:5432/nextcloud_prod?sslmode=disable
  username: nextcloud-prod
  password: "{{ postgres_nextcloud_prod_pass }}"
