---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: immich-daily-backup
  namespace: cloudnative-pg
spec:
  schedule: "0 2 * * *"
  backupOwnerReference: self
  cluster:
    name: immich
  immediate: true
  method: barmanObjectStore
