apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./coder
- ./paperless
- ./linkwarden
- ./langfuse
- ./immich
- ./nextcloud
- ./secret.yml
- ./role.yml
namespace: cloudnative-pg