apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: cloudnative-pg
  name: immich-secret-reader
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: immich-secret-reader-binding
  namespace: cloudnative-pg
subjects:
- kind: ServiceAccount
  name: immich
  namespace: cloudnative-pg
roleRef:
  kind: Role
  name: immich-secret-reader
  apiGroup: rbac.authorization.k8s.io
