apiVersion: v1
kind: Secret
metadata:
  name: nextcloud-db-url
  namespace: nextcloud
type: Opaque
stringData:
  url: postgres://nextcloud:{{ postgres_nextcloud_pass }}@nextcloud-rw.cloudnative-pg.svc.cluster.local:5432/nextcloud?sslmode=disable
  username: nextcloud
  password: "{{ postgres_nextcloud_pass }}"
