apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-prod-data-pvc
  namespace: nextcloud-prod
spec:
  storageClassName: ""
  volumeName: nextcloud-prod-data-pv
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
